# fly.toml app configuration file generated for guitarkeegan-2023-dry-butterfly-5629 on 2023-11-19T19:46:00-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "guitarkeegan-2023-dry-butterfly-5629"
primary_region = "lax"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
